channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.1.2
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - packaging==24.0
  - psutil==5.9.6
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
